defaults: &defaults
  url: "amqp://localhost:5672"
  exchange_name: "S2.exchange"
  durable: true
  empty_queue_disconnect_interval: 0

test:
  <<: *defaults

development:
  <<: *defaults
  queue_name: "warehousebuilder_queue"
  routing_keys:
  - '*.*.tube.*'
  - '*.*.spincolumn.*'
  - '*.*.tuberack.*'
  - '*.*.order.*'
  - '*.*.transfertubestotubes.*'

production:
  <<: *defaults
  url: "url"
  exchange_name: "psd.s2"
  queue_name: "psd.s2.audit"
