defaults: &defaults
  url: "amqp://localhost:5672"
  durable: true
  empty_queue_disconnect_interval: 0

test:
  <<: *defaults

development:
  <<: *defaults
  queue_name: "psd.s2.warehouse"

production:
  <<: *defaults
  url: "url"
  exchange_name: "psd.s2"
  queue_name: "psd.s2.audit"
